version: '3.9'
services:
  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    networks:
      - my_custom_network

  db:
    image: postgis/postgis:14-3.3
    restart: always
    shm_size: 1024mb
    volumes:
      - ./docker-pg-init-scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test123
      POSTGRES_DB: wemo
    ports:
      - '5432:5432'
    networks:
      - my_custom_network

  node_app:
    build:
      context: .
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    networks:
      - my_custom_network
    env_file:
      - .env.compose
    depends_on:
      - db
      - redis

networks:
  my_custom_network:
    driver: bridge
